# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: UseDotNet@2
  displayName: Install .NET SDK
  inputs:
    packageType: 'sdk'
    version: '10.0.x'

- script: dotnet restore FitGames/FitGames.DAL/FitGames.DAL.csproj
  displayName: Restore dependencies

- script: dotnet build FitGames/FitGames.DAL/FitGames.DAL.csproj --configuration Release
  displayName: Build project